---
- name: java repository add
  shell: add-apt-repository ppa:webupd8team/java
#- name: update all repositories
 # shell: apt-get update
#- name: install Java 8
 # shell: apt-get install oracle-java8-set-default
- name: install java 8
  apt: name=oracle-java8-installer state=latest install_recommends=no update_cache=yes
- name: java version verify
  shell: java -version
